-- MySQL Script generated by MySQL Workbench
-- Sun Apr 29 21:11:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Traveler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Traveler` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `hot` INT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `idHotel` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `star level` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `Location_idLocation` INT NOT NULL,
  PRIMARY KEY (`idHotel`),
  INDEX `Location_idLocation_idx` (`Location_idLocation` ASC),
  CONSTRAINT `Location_idLocation`
    FOREIGN KEY (`Location_idLocation`)
    REFERENCES `mydb`.`Location` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CreditCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CreditCard` (
  `number` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `security code` INT NOT NULL,
  `Traveler_idTraveler` INT NOT NULL,
  PRIMARY KEY (`number`),
  INDEX `Travler_idTraveler_idx` (`Traveler_idTraveler` ASC),
  CONSTRAINT `Travler_idTraveler`
    FOREIGN KEY (`Traveler_idTraveler`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `idPayment` INT NOT NULL,
  `price` INT NOT NULL,
  `CreditCard_number` INT NOT NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `CreditCard_number_idx` (`CreditCard_number` ASC),
  CONSTRAINT `CreditCard_number`
    FOREIGN KEY (`CreditCard_number`)
    REFERENCES `mydb`.`CreditCard` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `idRoom` INT NOT NULL,
  `price` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `Hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idRoom`),
  INDEX `Hotel_idHotel_idx` (`Hotel_idHotel` ASC),
  CONSTRAINT `Hotel_idHotel`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RoomState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RoomState` (
  `idRoomState` INT NOT NULL,
  `check in date` DATE NOT NULL,
  `check out date` DATE NOT NULL,
  `isAvaliable` TINYINT NOT NULL,
  `Room_idRoom` INT NOT NULL,
  PRIMARY KEY (`idRoomState`),
  INDEX `Room_idRoom_idx` (`Room_idRoom` ASC),
  CONSTRAINT `Room_idRoom`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `mydb`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `idReservation` INT NOT NULL,
  `hotel name` VARCHAR(45) NOT NULL,
  `room type` VARCHAR(45) NOT NULL,
  `check in date` DATE NOT NULL,
  `check out date` DATE NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  `Hotel_idHotel` INT NOT NULL,
  `Payment_idPayment` INT NOT NULL,
  `RoomState_idRoomState` INT NOT NULL,
  PRIMARY KEY (`idReservation`, `RoomState_idRoomState`),
  INDEX `idCustomer_idx` (`Customer_idCustomer` ASC),
  INDEX `Hotel_idHotel_idx` (`Hotel_idHotel` ASC),
  INDEX `Payment_idPayment_idx` (`Payment_idPayment` ASC),
  INDEX `fk_Reservation_RoomState1_idx` (`RoomState_idRoomState` ASC),
  CONSTRAINT `Customer_idCustomer`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `mydb`.`Traveler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Hotel_idHotel`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Payment_idPayment`
    FOREIGN KEY (`Payment_idPayment`)
    REFERENCES `mydb`.`Payment` (`idPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_RoomState1`
    FOREIGN KEY (`RoomState_idRoomState`)
    REFERENCES `mydb`.`RoomState` (`idRoomState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
